"""Initial authoritative schema"""
from alembic import op
import sqlalchemy as sa

revision = '63714acc0a95'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('query', sa.JSON(), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=True),
    sa.Column('exported_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('owner', sa.String(length=36), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('institutional_submissions',
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('transaction_id', sa.String(length=80), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('test_only', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('test_only = true'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'transaction_id')
    )
    op.create_table('sources',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('active_recipe_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('weight_datasets',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=120), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checksum')
    )
    op.create_table('index_series',
    sa.Column('weight_dataset_id', sa.String(length=36), nullable=False),
    sa.Column('methodology', sa.String(length=80), nullable=False),
    sa.Column('base_period', sa.String(length=7), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('values', sa.JSON(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['weight_dataset_id'], ['weight_datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('manifest', sa.JSON(), nullable=False),
    sa.Column('health', sa.String(length=30), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('live_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('successes', sa.Integer(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'version')
    )
    op.create_index(op.f('ix_recipes_source_id'), 'recipes', ['source_id'], unique=False)
    op.create_table('schedules',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cron', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_next_run_at'), 'schedules', ['next_run_at'], unique=False)
    op.create_table('jobs',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('schedule_id', sa.String(length=36), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_of', sa.String(length=36), nullable=True),
    sa.Column('state', sa.String(length=40), nullable=False),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('checkpoint', sa.String(length=80), nullable=False),
    sa.Column('owner', sa.String(length=36), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('wait_used_seconds', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('wait_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('challenge_id', sa.String(length=36), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['retry_of'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'scheduled_for')
    )
    op.create_index(op.f('ix_jobs_source_id'), 'jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    op.create_table('job_events',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_events_job_id'), 'job_events', ['job_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('airline', sa.String(length=120), nullable=False),
    sa.Column('flight_number', sa.String(length=60), nullable=True),
    sa.Column('cabin', sa.String(length=40), nullable=False),
    sa.Column('fare_class', sa.String(length=80), nullable=True),
    sa.Column('booking_window', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('taxes', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('total_fare', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('quality_flags', sa.JSON(), nullable=False),
    sa.Column('extraction_metadata', sa.JSON(), nullable=False),
    sa.CheckConstraint('origin <> destination', name='distinct_airports'),
    sa.CheckConstraint('total_fare > 0', name='positive_fare'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id', 'collected_at'),
    sa.UniqueConstraint('job_id', 'fingerprint', 'collected_at')
    )
    op.create_index('ix_observation_route', 'observations', ['origin', 'destination', 'departure_date', 'booking_window'], unique=False)
    op.create_index('ix_observation_source_time', 'observations', ['source_id', 'collected_at'], unique=False)
    op.create_table('operator_commands',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('challenge_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('result', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'idempotency_key')
    )
    op.create_index(op.f('ix_operator_commands_job_id'), 'operator_commands', ['job_id'], unique=False)
    op.create_table('repair_attempts',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('recipe_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('candidate', sa.JSON(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('candidate_recipe_id', sa.String(length=36), nullable=True),
    sa.Column('validation_job_id', sa.String(length=36), nullable=True),
    sa.Column('owner', sa.String(length=36), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['validation_job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repair_attempts')
    op.drop_index(op.f('ix_operator_commands_job_id'), table_name='operator_commands')
    op.drop_table('operator_commands')
    op.drop_index('ix_observation_source_time', table_name='observations')
    op.drop_index('ix_observation_route', table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_job_events_job_id'), table_name='job_events')
    op.drop_table('job_events')
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_schedules_next_run_at'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_recipes_source_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_table('index_series')
    op.drop_table('weight_datasets')
    op.drop_table('sources')
    op.drop_table('institutional_submissions')
    op.drop_table('exports')
    # ### end Alembic commands ###

